name: null

channels:
  - defaults

dependencies:
  - gxx_linux-64=7.3
  - jupyterlab=1.2
  - openmpi=4.0
  - pip=19.3
  - pip:
    - -r file:requirements.txt
    - pmdarima
    - fbprophet
  - python=3.7
  - tensorflow=2.0
  - pandas=0.25.1
  - numpy=1.16.5
  - joblib=0.13.2
  - xgboost=0.9
